In [2]:
import numpy as np

In [9]:
a = np.array(
    [[1, 2, 3, 3, 1], 
    [6, 8, 11, 10, 7]]
).transpose()
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [29]:
mean_a= np.mean(a,axis=0)

In [30]:
mean_a

array([2. , 8.4])

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [31]:
a_centered= a-mean_a


In [33]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [49]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]

In [50]:
a_centered_sp

8.0

In [53]:
a_centered.shape[0]-1

4

In [54]:
a_centered_sp / (a_centered.shape[0] - 1)


2.0